FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update
# OpenFOAM Required
RUN apt-get install -y build-essential
RUN apt-get install -y flex bison cmake zlib1g-dev libboost-system-dev libboost-thread-dev libopenmpi-dev openmpi-bin gnuplot libreadline-dev libncurses-dev libxt-dev
# Parallel processing required
RUN apt-get install -y libscotch-dev libcgal-dev 
# GUI apps required
RUN apt-get install -y wget x11-apps
RUN apt-get install -y python python-dev python3 python3-dev python3-pip
RUN apt-get install -y freeglut3 freeglut3-dev mesa-utils
RUN apt-get install -y qt5-default qt5-qmake qttools5-dev qtbase5-dev qtdeclarative5-dev libqt5x11extras5-dev libqt5svg5-dev qtxmlpatterns5-dev-tools
# Install CAD/CAE software from apt
RUN apt-get install -y freecad gmsh vim byobu git curl
# Installing Python packages for jupyter
RUN pip3 install jupyterlab scipy numpy pandas matplotlib seaborn

SHELL ["/bin/bash", "-c"]

# Installing OpenFOAM and Third Party from source
WORKDIR /opt/OpenFOAM/
RUN wget -O - https://sourceforge.net/projects/openfoam/files/v1912/ThirdParty-v1912.tgz | tar zx
RUN wget -O - https://sourceforge.net/projects/openfoam/files/v1912/OpenFOAM-v1912.tgz | tar zx
RUN chmod -R 775 OpenFOAM-v1912 ThirdParty-v1912
# Installing ParaView 5.6.3 with Python2.7(OMG!) from source
WORKDIR /opt/OpenFOAM/ThirdParty-v1912
RUN sed -i -e "s/bin\/sh/bin\/bash/" makeParaView
RUN source /opt/OpenFOAM/OpenFOAM-v1912/etc/bashrc && ./makeParaView -python2 -python-lib /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
# Installing OpenFOAM-v1912 from source
WORKDIR /opt/OpenFOAM/OpenFOAM-v1912
RUN source /opt/OpenFOAM/OpenFOAM-v1912/etc/bashrc && ./Allwmake
# [your docker img] echo 'alias of1912="source /home/OpenFOAM/OpenFOAM-v1912/etc/bashrc"' >> ~/.bashrc

# Installing Salome-Meca 2019.03 from binary
WORKDIR /opt/Salome-Meca
RUN wget -O - https://www.code-aster.org/FICHIERS/salome_meca-2019.0.3-1-universal.tgz | tar zx
RUN ./salome_meca-2019.0.3-1-universal.run -t /opt/Salome-Meca && rm ./salome_meca-2019.0.3-1-universal.run
RUN ln -s /usr/lib/x86_64-linux-gnu/libreadline.so /usr/lib/x86_64-linux-gnu/libreadline.so.7
# [your docker img] echo 'alias salome="/home/Salome-Meca/appli_V2019.0.3_universal/salome"' >> ~/.bashrc

# Installing julia-1.4.1 from binary
WORKDIR /opt/Julia
RUN wget -O - https://julialang-s3.julialang.org/bin/linux/x64/1.4/julia-1.4.1-linux-x86_64.tar.gz | tar zx
# [your docker img] echo 'alias julia="/home/Julia/julia-1.4.1/bin/julia"' >> ~/.bashrc
